
####################################################################################
# Generated by Vivado 2021.1 built on 'Thu Jun 10 19:36:33 MDT 2021' by 'xbuild'
# Command Used: write_xdc -constraints invalid unapplied_constraints.xdc
####################################################################################


####################################################################################
# Constraints from file : 'toplevel_gen.xdc'
####################################################################################

set_property -dict {PACKAGE_PIN "L10"  IOSTANDARD LVCMOS33} [get_ports aVN]
set_property -dict {PACKAGE_PIN "K9"  IOSTANDARD LVCMOS33} [get_ports aVP]
set_max_delay -from [get_cells *n_bushold/*ShiftRegister/SyncBusReset/*oLocalSigOutx/*FDCPEx -filter IS_SEQUENTIAL==true] -to [get_cells *n_bushold/*ShiftRegister/SyncBusReset/*iSigOut_msx/*FDCPEx -filter IS_SEQUENTIAL==true] -datapath_only 74.2425007499
set_max_delay -from [get_cells *ViControlx*rDerivedClkLostLock* -filter IS_SEQUENTIAL==true] -to [get_cells *ViControlx*bDerivedClkLostLock_ms* -filter IS_SEQUENTIAL==true] -datapath_only 148.4850014999
set_max_delay -from [get_cells *ViControlx*rGatedClkStartupErr* -filter IS_SEQUENTIAL==true] -to [get_cells *ViControlx*bGatedClkStartupErr_ms* -filter IS_SEQUENTIAL==true] -datapath_only 148.4850014999
set_max_delay -from [get_cells *ViControlx*rEnableDeassertionErr* -filter IS_SEQUENTIAL==true] -to [get_cells *ViControlx*bEnableDeassertionErr_ms* -filter IS_SEQUENTIAL==true] -datapath_only 148.4850014999
set_max_delay -from [get_cells *DiagramResetx*rDiagramResetAssertionErr* -filter IS_SEQUENTIAL==true] -to [get_cells *ViControlx*bDiagramResetAssertionErr_ms* -filter IS_SEQUENTIAL==true] -datapath_only 148.4850014999
set_max_delay -from [get_cells *ViControlx*tDiagramEnableOutReg* -filter IS_SEQUENTIAL==true] -to [get_cells *ViControlx*bEnableOut_ms* -filter IS_SEQUENTIAL==true] -datapath_only 100.0000000000
set_max_delay -from [get_pins {nirioSystemTopRoboRio_i/Ps7_i/Ps7_roboRIO_i/axi_iic_0/U0/X_IIC/*/C}] -to [get_pins {window/theVI/axi_iic_0*_ms_reg*/D}] 100.0
